/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package downloadsrmi;

/**
 *
 * @author irvingguerra
 */
public class DownloadsClient extends javax.swing.JPanel {

    /**
     * Creates new form DownloadsClient
     */
    public DownloadsClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWallpaper = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWallpaper.setText("jLabel1");
        add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblWallpaper;
    // End of variables declaration//GEN-END:variables
}
